### ISSUE TITLE
这个仅仅是NLU模块吧

### ISSUE THREAD

**Issue by MrRace** [panyang/WeatherBot_Rasa#1]
您好，你这个只是4个模块中的NLU模块吧。那其他模块还是使用原始的？可是原始仓库中request.txt都是0.XX版本的rasa，如果直接`pip install rasa`安装rasa则在Action的启动时候会由于版本问题而报错。所以，您能否将修改过的完整整个项目上传上来呢？多谢！

**Comment by panyang** [comment]
印象Action那个模块直接复用的，对接了一下天气api，没有什么改动，大概的流程请直接参考博文 http://www.52nlp.cn/rasa%e5%85%a5%e5%9d%91%e6%8c%87%e5%8d%97%e4%ba%8c-%e5%9f%ba%e4%ba%8e-rasa-%e6%9e%84%e5%bb%ba%e5%a4%a9%e6%b0%94%e6%9f%a5%e8%af%a2%e6%9c%ba%e5%99%a8%e4%ba%ba
